## 1. オブジェクトを作る (Object creation)

In [97]:
import numpy as np
import pandas as pd

In [98]:
np

In [99]:
pd

In [100]:
# 簡単に一列作る
# Seriesは、1次元のラベル付き配列型。データ型は任意。
s = pd.Series(data=[1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [101]:

# 2026年9月1日から6日間のデータ
dates = pd.date_range("20260901", periods=6)
dates

DatetimeIndex(['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04',
               '2026-09-05', '2026-09-06'],
              dtype='datetime64[ns]', freq='D')

In [102]:
# 行インデックス(index)に2026年9月1日からのデータを指定
# 各値にはランダムな数値を入れる
# DataFrameは、2次元のラベル付きデータ構造。行と列の両方にラベルが付けられる。
df = pd.DataFrame(np.random.randn(6, 4), index=dates)
df

                   0         1         2         3
2026-09-01  0.347432 -0.620768  0.562301  0.828095
2026-09-02  0.426273 -2.693026 -1.532093  2.033225
2026-09-03 -0.239480  0.513141 -1.492673  0.726074
2026-09-04 -0.666832  0.346450 -2.469202 -0.254601
2026-09-05 -0.322192  0.491082  1.498003  1.245006
2026-09-06  0.384076  1.752846  1.718162 -0.898708

In [103]:
## np.randomたちの検証
rndm_rand = np.random.rand(5)
rndm_sample = np.random.random_sample(5)
rndm_int = np.random.randint(1, 10, 5)
rndm_normal = np.random.randn(5)
print(rndm_rand)
print(rndm_sample)
print(rndm_int)
print(rndm_normal)

[0.69254563 0.15391517 0.83621457 0.717939   0.90725734]
[0.04895919 0.96488509 0.48206384 0.49077485 0.70426693]
[2 9 1 3 4]
[ 0.45618464 -0.07715411  0.34681274 -0.67229453  0.68529441]

In [104]:
# columnsで列名ABCDを設定
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ACED"))
df

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [105]:
# 辞書型のデータからDataFrameを作成する例
# キー部分が列名、値部分がデータとなる
# Cでのみindexを指定しているため、これが行インデックスとなる
## indexを別のキーでも設定するとTypeErrorとなる
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20260901"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2026-09-01  1.0  3   test  foo
1  1.0 2026-09-01  1.0  3  train  foo
2  1.0 2026-09-01  1.0  3   test  foo
3  1.0 2026-09-01  1.0  3  train  foo

In [106]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

## 2. データを表示する (Viewing data)

In [107]:
# 先頭のx行を表示
df.head(2)

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958

In [108]:
# 末尾のx行を表示
df.tail(2)

                   A         C         E         D
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [109]:

df.index

DatetimeIndex(['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04',
               '2026-09-05', '2026-09-06'],
              dtype='datetime64[ns]', freq='D')

In [110]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [111]:
# numpyで操作しやすいデータに変換
df.to_numpy()

array([[ 0.5268752 , -0.30447329,  1.78934722, -0.64776304],
       [ 0.11195028, -0.99459942, -0.04230941, -0.56795789],
       [ 1.15402781,  1.32792532,  1.56055775,  1.35690265],
       [-0.18513866,  1.90224391, -0.18427941, -1.60127027],
       [ 1.0428341 , -0.05845788, -1.61025622, -0.12088367],
       [ 0.10961599,  1.44480408, -0.37933039,  0.59891635]])

In [112]:
# 上記の操作を行っても元のデータは上書きされない
df

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [113]:
df2.to_numpy()

array([[1.0, Timestamp('2026-09-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-09-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-09-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-09-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [114]:
# describe()メソッドで各列の簡単な統計を取れる
## stdは標準偏差
df2.describe()

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2026-09-01 00:00:00  1.0  3.0
min    1.0  2026-09-01 00:00:00  1.0  3.0
25%    1.0  2026-09-01 00:00:00  1.0  3.0
50%    1.0  2026-09-01 00:00:00  1.0  3.0
75%    1.0  2026-09-01 00:00:00  1.0  3.0
max    1.0  2026-09-01 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [115]:
# Tメソッドで行と列を入れ替えたデータを取得可能
df.T

   2026-09-01  2026-09-02  2026-09-03  2026-09-04  2026-09-05  2026-09-06
A    0.526875    0.111950    1.154028   -0.185139    1.042834    0.109616
C   -0.304473   -0.994599    1.327925    1.902244   -0.058458    1.444804
E    1.789347   -0.042309    1.560558   -0.184279   -1.610256   -0.379330
D   -0.647763   -0.567958    1.356903   -1.601270   -0.120884    0.598916

In [116]:
# 同様に、transpose()メソッドでも行と列を入れ替えたデータを取得可能
df.transpose()

   2026-09-01  2026-09-02  2026-09-03  2026-09-04  2026-09-05  2026-09-06
A    0.526875    0.111950    1.154028   -0.185139    1.042834    0.109616
C   -0.304473   -0.994599    1.327925    1.902244   -0.058458    1.444804
E    1.789347   -0.042309    1.560558   -0.184279   -1.610256   -0.379330
D   -0.647763   -0.567958    1.356903   -1.601270   -0.120884    0.598916

In [117]:
# sort_index()メソッドでindexとcolumnsを昇順に並べ替えたデータを取得可能
df.sort_index()

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [118]:
# axis=0またはaxis='index'で行方向、axis=1またはaxis='columns'で列方向に沿って並べ替え可能
# 引数ascendingにFalseを指定すると、並び順が降順になる
# ただし、インデックスが文字列のリストの場合、リストの順番ではなくアルファベット順に並べ替えられる
df.sort_index(axis=1, ascending=False)

                   E         D         C         A
2026-09-01  1.789347 -0.647763 -0.304473  0.526875
2026-09-02 -0.042309 -0.567958 -0.994599  0.111950
2026-09-03  1.560558  1.356903  1.327925  1.154028
2026-09-04 -0.184279 -1.601270  1.902244 -0.185139
2026-09-05 -1.610256 -0.120884 -0.058458  1.042834
2026-09-06 -0.379330  0.598916  1.444804  0.109616

In [119]:
# sort_values()メソッドで、指定した行or列の値に沿って並べ替えたデータを取得可能
df.sort_values(by="C")

                   A         C         E         D
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-06  0.109616  1.444804 -0.379330  0.598916
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270

In [120]:
# 列で並び替える場合は、byに列名を渡して、axis=1またはaxis='columns'を指定する必要がある
df.sort_values(by="2026-09-01", axis=1)

                   D         C         A         E
2026-09-01 -0.647763 -0.304473  0.526875  1.789347
2026-09-02 -0.567958 -0.994599  0.111950 -0.042309
2026-09-03  1.356903  1.327925  1.154028  1.560558
2026-09-04 -1.601270  1.902244 -0.185139 -0.184279
2026-09-05 -0.120884 -0.058458  1.042834 -1.610256
2026-09-06  0.598916  1.444804  0.109616 -0.379330

## 3. データを選択する (Selection)

### 単純なデータ取得 (Getitem ([]))

#### 列単位

In [121]:
# A列のデータを取得
df["A"]
# df.Aでも可
## Freqはデータの頻度属性で、Dは日次データ（1日毎のデータ）であることを指す
## Dの他に、W（週次）、M（月次）、Q（四半期）、Y（年次）、H（時間）、M（分）、S（秒）などがある

2026-09-01    0.526875
2026-09-02    0.111950
2026-09-03    1.154028
2026-09-04   -0.185139
2026-09-05    1.042834
2026-09-06    0.109616
Freq: D, Name: A, dtype: float64

In [122]:
# A列、C列のデータを取得
df[["A", "C"]]

                   A         C
2026-09-01  0.526875 -0.304473
2026-09-02  0.111950 -0.994599
2026-09-03  1.154028  1.327925
2026-09-04 -0.185139  1.902244
2026-09-05  1.042834 -0.058458
2026-09-06  0.109616  1.444804

#### 行単位

In [123]:
# 先頭4行表示
df[0:3]

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903

In [124]:
# 2026年9月2日から2026年9月4日まで表示
df['20260902':'20260904']

                   A         C         E         D
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270

### ラベルを指定してデータを選択

locメソッドでは、DataFrame内で条件を満たした行、列を抽出できる。<br>
通常の参照と異なり、行と列両方の条件を指定できる。

In [125]:
# locメソッドで、行インデックスを指定してデータを列として取得可能
# 例えば、2026年9月1日（index0番目）のデータを取得する場合は、以下のように記述する
df.loc[dates[0]]

A    0.526875
C   -0.304473
E    1.789347
D   -0.647763
Name: 2026-09-01 00:00:00, dtype: float64

In [126]:
# 単一データの取得も可能
df.loc[dates[0], "A"]

# 単一データ取得の場合、locよりatメソッドの方が高速に取得可能
df.at[dates[0], "A"]

np.float64(0.5268751986121081)

In [127]:
# 列名で指定する場合は、locメソッドの第2引数に列名を渡す
# この時第1引数に:を指定することで、全行を取得することができる
df.loc[:, ["A", "C"]]
# df[["A", "C"]] と出力結果は同じ

                   A         C
2026-09-01  0.526875 -0.304473
2026-09-02  0.111950 -0.994599
2026-09-03  1.154028  1.327925
2026-09-04 -0.185139  1.902244
2026-09-05  1.042834 -0.058458
2026-09-06  0.109616  1.444804

In [128]:
# 第1引数にindex番号を指定すれば、特定の行のデータを取得可能
df.loc[dates[1]:dates[3], ["A", "C"]]

# df.loc["20260902":"20260904", ["A", "C"]]
# でも同様の結果になる

                   A         C
2026-09-02  0.111950 -0.994599
2026-09-03  1.154028  1.327925
2026-09-04 -0.185139  1.902244

In [ ]:
# 条件指定しての抽出も可能
# 行の条件表記なので第1引数に記載
df.loc[df["A"] > 0]

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [ ]:
# 条件指定で絞り込んだうえで、特定の列を取得することも可能
# 列を指定するなら単純に第2引数を指定すればOK
df.loc[df["A"] > 0, ["C"]]

                   C
2026-09-01 -0.304473
2026-09-02 -0.994599
2026-09-03  1.327925
2026-09-05 -0.058458
2026-09-06  1.444804

In [ ]:
# locを使って行で絞り込む方法はあるのか？ →ある
# 真偽値リストを使ったデータ指定が役に立つ
# 列の条件表記なので第2引数に記載、第1引数は全表示の:を指定する
df.loc[:, df.loc[dates[0]] > 0]

                   A         E
2026-09-01  0.526875  1.789347
2026-09-02  0.111950 -0.042309
2026-09-03  1.154028  1.560558
2026-09-04 -0.185139 -0.184279
2026-09-05  1.042834 -1.610256
2026-09-06  0.109616 -0.379330

In [151]:
# ちなみに列指定の中身はこのようになっている
df.loc[dates[0]] > 0

A     True
C    False
E     True
D    False
Name: 2026-09-01 00:00:00, dtype: bool

In [171]:
# さらに表示する行を絞る場合はこのように記載
# 行を指定するなら単純に第1引数を指定すればOK
df.loc[[dates[0]], df.loc[dates[0]] > 0]

# 返り値がSeries型でよければ下記でOK
# df.loc[dates[0], df.loc[dates[0]] > 0]

                   A         E
2026-09-01  0.526875  1.789347

### 位置を指定してデータを選択

In [172]:
df

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [ ]:
# 4行目を1列として取得
# locとの違いは、ラベル名ではなく行番号で指定する点
df.iloc[3]

A   -0.185139
C    1.902244
E   -0.184279
D   -1.601270
Name: 2026-09-04 00:00:00, dtype: float64

In [ ]:
# 4行目から5行目、1列目から2列目を取得
# コロンで指定する場合、末尾の番号は無視されるので注意
df.iloc[3:5, 0:2]

                   A         C
2026-09-04 -0.185139  1.902244
2026-09-05  1.042834 -0.058458

In [ ]:
# リスト型での指定も可能
df.iloc[[1, 2, 4], [0, 2]]

                   A         E
2026-09-02  0.111950 -0.042309
2026-09-03  1.154028  1.560558
2026-09-05  1.042834 -1.610256

In [ ]:
# locと同様に、ilocでも:指定で全表示
df.iloc[1:3, :]

                   A         C         E         D
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903

In [179]:
df.iloc[:, 1:3]

                   C         E
2026-09-01 -0.304473  1.789347
2026-09-02 -0.994599 -0.042309
2026-09-03  1.327925  1.560558
2026-09-04  1.902244 -0.184279
2026-09-05 -0.058458 -1.610256
2026-09-06  1.444804 -0.379330

In [183]:
# 単一データの取得も可能
df.iloc[1, 1]

# loc同様、atメソッドでより高速になる
df.iat[1, 1]

np.float64(-0.994599416490899)

### 条件インデックス参照 (Boolean indexing)

In [ ]:
df

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

#### 単一列の値を使用してデータを選択

In [ ]:
# A列データが0より大きい行を取得
df[df['A'] > 0]
# df['A'] は df.A に置換可能

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [189]:
# 上の処理は、実際は真偽値のリストで行を絞り込んでいる
df['A'] > 0

2026-09-01     True
2026-09-02     True
2026-09-03     True
2026-09-04    False
2026-09-05     True
2026-09-06     True
Freq: D, Name: A, dtype: bool

#### ブール条件が満たされるDataFrameから値を選択

In [ ]:
# 0より大きいデータのみを取得（条件を満たさない場合NaNになる）
df[df > 0]

                   A         C         E         D
2026-09-01  0.526875       NaN  1.789347       NaN
2026-09-02  0.111950       NaN       NaN       NaN
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04       NaN  1.902244       NaN       NaN
2026-09-05  1.042834       NaN       NaN       NaN
2026-09-06  0.109616  1.444804       NaN  0.598916

In [ ]:
# これも真偽値のテーブルによって絞り込まれている
df > 0

                A      C      E      D
2026-09-01   True  False   True  False
2026-09-02   True  False  False  False
2026-09-03   True   True   True   True
2026-09-04  False   True  False  False
2026-09-05   True  False  False  False
2026-09-06   True   True  False   True

#### isin()メソッドでフィルタリング

In [197]:
df3 = df.copy()
df3["B"] = ["one", "one", "two", "three", "four", "three"]
df3

                   A         C         E         D      B
2026-09-01  0.526875 -0.304473  1.789347 -0.647763    one
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958    one
2026-09-03  1.154028  1.327925  1.560558  1.356903    two
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270  three
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884   four
2026-09-06  0.109616  1.444804 -0.379330  0.598916  three

In [199]:
df3[df3["B"].isin(["two", "four"])]

                   A         C         E         D     B
2026-09-03  1.154028  1.327925  1.560558  1.356903   two
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884  four

In [ ]:
# isin()メソッドは、指定した値が含まれているかどうかを判定するメソッド
# TrueかFalseを返す
df3["B"].isin(["two", "four"])

2026-09-01    False
2026-09-02    False
2026-09-03     True
2026-09-04    False
2026-09-05     True
2026-09-06    False
Freq: D, Name: B, dtype: bool

In [204]:
df3["B"]

2026-09-01      one
2026-09-02      one
2026-09-03      two
2026-09-04    three
2026-09-05     four
2026-09-06    three
Freq: D, Name: B, dtype: object

In [201]:
type(df3["B"])

pandas.core.series.Series

### 値の追加・更新 (Setting)

#### 新しい列を設定すると、データが自動的にインデックス基準で整列される

In [205]:
df

                   A         C         E         D
2026-09-01  0.526875 -0.304473  1.789347 -0.647763
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958
2026-09-03  1.154028  1.327925  1.560558  1.356903
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884
2026-09-06  0.109616  1.444804 -0.379330  0.598916

In [207]:
s1 = pd.Series(
   [1, 2, 3, 4, 5, 6],
   index=pd.date_range("20260902", periods=6))
s1

2026-09-02    1
2026-09-03    2
2026-09-04    3
2026-09-05    4
2026-09-06    5
2026-09-07    6
Freq: D, dtype: int64

In [ ]:
df["F"] = s1
df

# このとき、2026-09-07行は増えない

                   A         C         E         D    F
2026-09-01  0.526875 -0.304473  1.789347 -0.647763  NaN
2026-09-02  0.111950 -0.994599 -0.042309 -0.567958  1.0
2026-09-03  1.154028  1.327925  1.560558  1.356903  2.0
2026-09-04 -0.185139  1.902244 -0.184279 -1.601270  3.0
2026-09-05  1.042834 -0.058458 -1.610256 -0.120884  4.0
2026-09-06  0.109616  1.444804 -0.379330  0.598916  5.0

#### ラベル、位置、NumPy配列の代入による値の設定

In [ ]:
df.at[dates[0], "A"] = 0                    # 1行目A列の値を0に
df.iat[0, 1] = 0                            # 1行目C列(2列目)の値を0に
df.loc[:, "D"] = np.array([5] * len(df))    # D列に値5、長さ6(lenでdfに合わせた)の配列を代入
df

                   A         C         E    D    F
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0
2026-09-05  1.042834 -0.058458 -1.610256  5.0  4.0
2026-09-06  0.109616  1.444804 -0.379330  5.0  5.0

In [213]:
df3 = df.copy()
df3[df3 > 0] = -df3
df3

                   A         C         E    D    F
2026-09-01  0.000000  0.000000 -1.789347 -5.0  NaN
2026-09-02 -0.111950 -0.994599 -0.042309 -5.0 -1.0
2026-09-03 -1.154028 -1.327925 -1.560558 -5.0 -2.0
2026-09-04 -0.185139 -1.902244 -0.184279 -5.0 -3.0
2026-09-05 -1.042834 -0.058458 -1.610256 -5.0 -4.0
2026-09-06 -0.109616 -1.444804 -0.379330 -5.0 -5.0

## 4. 欠損データ (Missing data)

NumPyにおいて、np.nanは欠損値を表す。
デフォルトでは計算に組み込まれない。

インデックスを再作成すると、指定の軸のインデックスを変更/追加/削除可能。返り値はデータのコピー。

In [216]:
df

                   A         C         E    D    F
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0
2026-09-05  1.042834 -0.058458 -1.610256  5.0  4.0
2026-09-06  0.109616  1.444804 -0.379330  5.0  5.0

#### reindexで作り直し

In [250]:
# dfを参照し、5番目までの行名(index)と、すべての列名にGを追加したものを取得
# reindexが通常の参照と異なるのは、行名や列名を指定して新しいDataFrameを作成できる点
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["G"])
df1

                   A         C         E    D    F   G
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0 NaN
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0 NaN
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0 NaN

In [251]:
# 2行目までのG列に1を代入
df1.loc[dates[0]:dates[1], "G"] = 1
df1

                   A         C         E    D    F    G
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN  1.0
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0  NaN
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0  NaN

In [252]:
# 通常の参照だと、呼び出しは可能だが行や列の追加はできない。
df.loc[dates[0:4], list(df.columns)]

                   A         C         E    D    F
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0

In [253]:
# indexに追加も可能だが、今回はデータ型が日付だったため、単純に+で追加はできない
# やるとしたらunionを使う必要がある
df0 = df.reindex(
    index= df.index.union([pd.Timestamp("20260907")]), 
    columns= list(df.columns) + ["G"])
df0

                   A         C         E    D    F   G
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0 NaN
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0 NaN
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0 NaN
2026-09-05  1.042834 -0.058458 -1.610256  5.0  4.0 NaN
2026-09-06  0.109616  1.444804 -0.379330  5.0  5.0 NaN
2026-09-07       NaN       NaN       NaN  NaN  NaN NaN

#### `DataFrame.dropna()` でデータが欠落している行を削除

In [263]:
# dropnaはNaNを含むレコード(行)を削除
# 代入していないので上書きではない
df1.dropna(how="any")

                  A         C         E    D    F    G
2026-09-02  0.11195 -0.994599 -0.042309  5.0  1.0  1.0

#### `DataFrame.fillna()` で欠損データを埋める

In [260]:
# NaNを5に置き換える
df1.fillna(value=5)

                   A         C         E    D    F    G
2026-09-01  0.000000  0.000000  1.789347  5.0  5.0  1.0
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0  5.0
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0  5.0

In [261]:
# df1=で代入しない限り、df1の中身は上書きされない
df1

                   A         C         E    D    F    G
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN  1.0
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0  NaN
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0  NaN

#### `DataFrame.isna()` でNaN値の位置を示すブールマスクを取得

In [264]:
pd.isna(df1)

                A      C      E      D      F      G
2026-09-01  False  False  False  False   True  False
2026-09-02  False  False  False  False  False  False
2026-09-03  False  False  False  False  False   True
2026-09-04  False  False  False  False  False   True

## 5. 操作 (Operations)

### 統計 (Stats)

In [265]:
df

                   A         C         E    D    F
2026-09-01  0.000000  0.000000  1.789347  5.0  NaN
2026-09-02  0.111950 -0.994599 -0.042309  5.0  1.0
2026-09-03  1.154028  1.327925  1.560558  5.0  2.0
2026-09-04 -0.185139  1.902244 -0.184279  5.0  3.0
2026-09-05  1.042834 -0.058458 -1.610256  5.0  4.0
2026-09-06  0.109616  1.444804 -0.379330  5.0  5.0

In [268]:
df.dtypes

A    float64
C    float64
E    float64
D    float64
F    float64
dtype: object

In [ ]:
# 統計において、デフォルトではNaNは無視される
# Fの平均値は (1+2+3+4+5)/5 で 3 になっている
# 引数を指定しないと、列ごとの計算結果を返す
df.mean()

# df.mean(0) でも結果は同様

A    0.372215
C    0.603653
E    0.188955
D    5.000000
F    3.000000
dtype: float64

In [270]:
# 行ごとの計算をしたい場合は、引数にaxis=1を指定
df.mean(axis=1)

# df.mean(1) でも結果は同様

2026-09-01    1.697337
2026-09-02    1.015008
2026-09-03    2.208502
2026-09-04    1.906565
2026-09-05    1.674824
2026-09-06    2.235018
Freq: D, dtype: float64

## 再開前のメモ
- **新しいターミナルを開くたびに、`source .venv/bin/activate`を打つ**のを忘れないようにする（忘れると素のPython環境で動いてしまいます）
- 抜けるときは`deactivate`と打つ