## 再開前のメモ
- **新しいターミナルを開くたびに、`source .venv/bin/activate`を打つ**のを忘れないようにする（忘れると素のPython環境で動いてしまいます）
- 抜けるときは`deactivate`と打つ

In [3]:
import pandas as pd

df = pd.read_csv("sample_schedule.csv")
df.head()

# 読み込みの時点で日付列を日付型に変換
# df = pd.read_csv("sample_schedule.csv", parse_dates=["日付"])

  営業担当者         日付        予定
0     A  2026/9/28        休み
1     A  2026/9/29    勉強会、巡回
2     A  2026/9/30        研修
3     A  2026/10/1        休み
4     A  2026/10/2  勉強会、月初作業

In [4]:
df.head(3)   # 先頭3行だけ表示

  営業担当者         日付      予定
0     A  2026/9/28      休み
1     A  2026/9/29  勉強会、巡回
2     A  2026/9/30      研修

In [3]:
df.shape     # (行数, 列数) を確認

(21, 3)

In [4]:
df.info()    # 各列の型や欠損の有無を確認

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   営業担当者   21 non-null     object
 1   日付      21 non-null     object
 2   予定      21 non-null     object
dtypes: object(3)
memory usage: 632.0+ bytes

In [6]:
df["日付"] = pd.to_datetime(df["日付"]) # 日付列のデータを日付データ型に変換
df.dtypes

営業担当者            object
日付       datetime64[ns]
予定               object
dtype: object

In [7]:
df["日付"].dt.month        # 月だけ取り出す

0      9
1      9
2      9
3     10
4     10
5     10
6     10
7      9
8      9
9      9
10    10
11    10
12    10
13    10
14     9
15     9
16     9
17    10
18    10
19    10
20    10
Name: 日付, dtype: int32

In [8]:
df["日付"].dt.day_name()   # 曜日名を取り出す

0        Monday
1       Tuesday
2     Wednesday
3      Thursday
4        Friday
5      Saturday
6        Sunday
7        Monday
8       Tuesday
9     Wednesday
10     Thursday
11       Friday
12     Saturday
13       Sunday
14       Monday
15      Tuesday
16    Wednesday
17     Thursday
18       Friday
19     Saturday
20       Sunday
Name: 日付, dtype: object

In [9]:
df["日付"].dt.day   # 日だけを取り出す

0     28
1     29
2     30
3      1
4      2
5      3
6      4
7     28
8     29
9     30
10     1
11     2
12     3
13     4
14    28
15    29
16    30
17     1
18     2
19     3
20     4
Name: 日付, dtype: int32

In [11]:
# df["金額"]              # 1列だけ取り出す
df[["日付", "予定"]]  # 複数列は二重の角括弧で指定する

           日付        予定
0  2026-09-28        休み
1  2026-09-29    勉強会、巡回
2  2026-09-30        研修
3  2026-10-01        休み
4  2026-10-02  勉強会、月初作業
5  2026-10-03  MTG、月初作業
6  2026-10-04      月初作業
7  2026-09-28        巡回
8  2026-09-29       勉強会
9  2026-09-30        巡回
10 2026-10-01        休み
11 2026-10-02        休み
12 2026-10-03  MTG、月初作業
13 2026-10-04      月初作業
14 2026-09-28        巡回
15 2026-09-29    勉強会、巡回
16 2026-09-30   本社研修、巡回
17 2026-10-01        休み
18 2026-10-02  勉強会、月初作業
19 2026-10-03  MTG、月初作業
20 2026-10-04      月初作業

In [18]:
# df[df["営業担当者"] == "A"]        # Aの予定だけ
# df[df["日付"] >= "2026-09-30"]              # 9月30日以降
df[(df["営業担当者"] == "A") & (df["日付"] >= "2026-09-30")]  # 両方の条件

  営業担当者         日付        予定
2     A 2026-09-30        研修
3     A 2026-10-01        休み
4     A 2026-10-02  勉強会、月初作業
5     A 2026-10-03  MTG、月初作業
6     A 2026-10-04      月初作業

In [19]:
df.groupby("営業担当者")["日付"]

In [37]:
df_kakeibo = pd.read_csv("sample_kakeibo.csv",parse_dates=["日付"])
df_kakeibo.head()

          日付 カテゴリ    金額
0 2026-09-01   食費  1200
1 2026-09-02  交通費   480
2 2026-09-02   食費   480
3 2026-09-03   食費   850
4 2026-09-03   食費   700

In [38]:
df_kakeibo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日付      14 non-null     datetime64[ns]
 1   カテゴリ    14 non-null     object
 2   金額      14 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 464.0+ bytes

In [42]:
# df_kakeibo.groupby("カテゴリ")["金額"].sum()     # カテゴリ別の金額合計
df_kakeibo.groupby(["カテゴリ","日付"]).sum()    # カテゴリ別に日付ごとの金額合計
# df_kakeibo.groupby(["カテゴリ","日付"],as_index=False).sum()    # index結合をしない
# df_kakeibo.groupby("日付").count()   # カテゴリ別の件数

                   金額
カテゴリ 日付
交通費  2026-09-02   480
     2026-09-07   240
娯楽   2026-09-04  3000
     2026-09-06  1800
     2026-09-09  1800
日用品  2026-09-06   620
     2026-09-10  1350
食費   2026-09-01  1200
     2026-09-02   480
     2026-09-03  1550
     2026-09-05  1500
     2026-09-06   980
     2026-09-08   980

In [43]:
df_kakeibo["月"] = df_kakeibo["日付"].dt.month
df_kakeibo.groupby("月")["金額"].sum()

月
9    15980
Name: 金額, dtype: int64

In [44]:
df_kakeibo.head()

          日付 カテゴリ    金額  月
0 2026-09-01   食費  1200  9
1 2026-09-02  交通費   480  9
2 2026-09-02   食費   480  9
3 2026-09-03   食費   850  9
4 2026-09-03   食費   700  9

In [47]:
df.groupby(["日付","営業担当者"]).sum()

                        予定
日付         営業担当者
2026-09-28 A            休み
           B            巡回
           C            巡回
2026-09-29 A        勉強会、巡回
           B           勉強会
           C        勉強会、巡回
2026-09-30 A            研修
           B            巡回
           C       本社研修、巡回
2026-10-01 A            休み
           B            休み
           C            休み
2026-10-02 A      勉強会、月初作業
           B            休み
           C      勉強会、月初作業
2026-10-03 A      MTG、月初作業
           B      MTG、月初作業
           C      MTG、月初作業
2026-10-04 A          月初作業
           B          月初作業
           C          月初作業

In [48]:
schedule_table = df.pivot(
    index="日付",
    columns="営業担当者",
    values="予定"
)

schedule_table

営業担当者              A         B         C
日付
2026-09-28        休み        巡回        巡回
2026-09-29    勉強会、巡回       勉強会    勉強会、巡回
2026-09-30        研修        巡回   本社研修、巡回
2026-10-01        休み        休み        休み
2026-10-02  勉強会、月初作業        休み  勉強会、月初作業
2026-10-03  MTG、月初作業  MTG、月初作業  MTG、月初作業
2026-10-04      月初作業      月初作業      月初作業

In [52]:
df_expanded = (
    df.assign(予定=df["予定"].str.split("、")) # 予定列のリストを"、"区切りで分解しリストに格納 assignで変更箇所を置き換えたDataFrameを返す
      .explode("予定")
      .reset_index(drop=True)
)

df_expanded.head()

  営業担当者         日付   予定
0     A 2026-09-28   休み
1     A 2026-09-29  勉強会
2     A 2026-09-29   巡回
3     A 2026-09-30   研修
4     A 2026-10-01   休み

In [58]:
pd.pivot_table(
    df_expanded,
    index="日付",
    columns="営業担当者",
    values="予定",
    aggfunc=lambda schedules: "、".join(schedules),
    # aggfunc=list # リスト型で持つ場合はこっち
    fill_value=""
)

営業担当者                 A            B            C
日付
2026-09-28         [休み]         [巡回]         [巡回]
2026-09-29    [勉強会, 巡回]        [勉強会]    [勉強会, 巡回]
2026-09-30         [研修]         [巡回]   [本社研修, 巡回]
2026-10-01         [休み]         [休み]         [休み]
2026-10-02  [勉強会, 月初作業]         [休み]  [勉強会, 月初作業]
2026-10-03  [MTG, 月初作業]  [MTG, 月初作業]  [MTG, 月初作業]
2026-10-04       [月初作業]       [月初作業]       [月初作業]